EXTENDS:
    - "https://raw.githubusercontent.com/llaville/.github/refs/heads/master/.mega-linter-base.yml"
    - .mega-linter-base.yml
PHP_PHPSTAN_CLI_EXECUTABLE: "/tmp/lint/vendor/bin/phpstan" # force to use PHPStan locally version when additional extensions are required
PHP_PHPSTAN_DISABLE_ERRORS: false # project is now compatible PHPStan 2.x
