ENABLE:
    - ACTION
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_PRETTIER
    - JSON_V8R
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_BUILTIN
    - PHP_PSALM
    - PHP_PHPCSFIXER
    - YAML_V8R
PRINT_ALL_FILES: false
