PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (vendor/)
ENABLE:
    - EDITORCONFIG
    - JSON
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - JSON_V8R
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_PHPSTAN
    - PHP_PSALM
    - YAML_V8R
EDITORCONFIG_EDITORCONFIG_CHECKER_CLI_LINT_MODE: project
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: "(composer.json)"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdown-lint.json"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
PHP_PHPCS_CONFIG_FILE: ".phpcs.xml.dist"
PHP_PHPCS_ARGUMENTS: "-n"
PHP_PHPSTAN_CONFIG_FILE: "phpstan.neon.dist"
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(\\.github)"
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(\\.github)"
