name: Tests

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    php_tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-18.04
                php:
                    - 7.2
                    - 7.3
                    - 7.4
                    - 8.0
                include:
                    -
                        os: ubuntu-18.04
                        php: 7.2
                        extensions: amqp,apc,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gender,geoip,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,jsmin,json,ldap,libxml,lzf,mailparse,mbstring,memcache,memcached,msgpack,mysqli,oci8,odbc,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,propro,pecl_http-3.2.4,rar,readline,recode,redis,reflection,session,shmop,simplexml,snmp,soap,sockets,solr,spl,sqlite3,ssh2,standard,stomp,sync,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,uopz,uploadprogress,wddx,xhprof,xml,xmldiff,xmlreader,xmlrpc,xmlwriter,xsl,yaml,zip,zlib
                    -
                        os: ubuntu-18.04
                        php: 7.3
                        extensions: amqp,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gender,geoip,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,jsmin,json,ldap,libxml,lzf,mailparse,mbstring,memcache,memcached,msgpack,mysqli,oci8,odbc,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,propro,pecl_http-3.2.4,rar,readline,recode,redis,reflection,session,shmop,simplexml,snmp,soap,sockets,solr,spl,sqlite3,ssh2,standard,stomp,sync,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,uopz,uploadprogress,wddx,xhprof,xml,xmldiff,xmlreader,xmlrpc,xmlwriter,xsl,yaml,zip,zlib
                    -
                        os: ubuntu-18.04
                        php: 7.4
                        extensions: amqp,apc,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,exif,fileinfo,filter,ftp,gd,gender,geoip,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,jsmin,json,ldap,libxml,lzf,mailparse,mbstring,memcache,memcached,msgpack,mysqli,oci8,odbc,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,propro,pecl_http-3.2.4,rar,readline,redis,reflection,session,shmop,simplexml,snmp,soap,sockets,solr,spl,sqlite3,ssh2,standard,stomp,sync,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,uopz,uploadprogress,xhprof,xml,xmldiff,xmlreader,xmlrpc,xmlwriter,xsl,yaml,zip,zlib
                    -
                        os: ubuntu-18.04
                        php: 8.0
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mailparse,mbstring,memcache,memcached,msgpack,mysql,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,pecl_http,rar,readline,redis,reflection,session,shmop,simplexml,sockets,spl,sqlite,sqlite3,standard,sysvmsg,sysvsem,sysvshm,tokenizer,xdebug,xhprof,xml,xmldiff,xmlrpc-beta,xmlreader,xmlwriter,xsl,yac,zip,zlib

        name: "Test PHP ${{ matrix.php }} on ${{ matrix.os }}"

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2

            -
                name: Setup Librairies
                run: sudo apt-fast install libcurl4-openssl-dev -y

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}

            -   # https://github.com/actions/cache/blob/main/examples.md#php---composer
                name: Get Composer Cache Directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-
                        ${{ runner.os }}-php-
                        ${{ runner.os }}-

            -
                name: Install Composer dependencies
                run: composer update --no-progress --prefer-dist --optimize-autoloader

            -
                name: Build Database
                run: |
                    vendor/bin/doctrine orm:schema-tool:create
                    bin/compatinfo-db db:init

            -
                name: Check Database
                run: |
                    bin/compatinfo-db diagnose
                    bin/compatinfo-db db:list --all

            -
                name: Unit tests
                run: vendor/bin/simple-phpunit --verbose --testsuite ${{ matrix.extensions }}
