---
name: Release

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    build:
        uses: llaville/.github/.github/workflows/release.yml@master
        with:
            repository: ${{ github.repository }}
            box-output: bin/compatinfo-db.phar
            release-draft: true
            legacy: false
