---
name: Unit Tests

on:
    push:
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches: [master]
        paths-ignore:
            - 'docs/**'

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}

    unit_tests:
        needs: lint_files

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        os: ubuntu-latest
                        php: 7.4
                        extensions: amqp,apc,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,exif,fileinfo,filter,ftp,gd,gender,geoip,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,jsmin,json,ldap,libxml,lzf,mailparse,mbstring,mcrypt,memcache,memcached,msgpack,mysqli,oci8-2.2.0,odbc,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,propro,pecl_http-3.2.4,rar,rdkafka,readline,redis,reflection,session,shmop,simplexml,snmp,soap,sockets,solr,spl,sqlite3,ssh2,standard,stomp,sync,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,uploadprogress,uuid,xhprof,xlswriter,xml,xmldiff,xmlreader,xmlrpc,xmlwriter,xsl,yaml,zip,zlib
                        tools: phpunit
                    -
                        os: ubuntu-latest
                        php: 8.0
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mailparse,mbstring,mcrypt,memcache,memcached,msgpack,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,pecl_http,rar,rdkafka,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xlswriter,xml,xmldiff,xmlreader,xmlwriter,xsl,yac,zip,zlib
                        tools: phpunit
                    -
                        os: ubuntu-latest
                        php: 8.1
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,mcrypt,memcache,memcached,msgpack,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xsl,yac,zip,zlib
                        tools: phpunit
                    -
                        os: ubuntu-latest
                        php: 8.2
                        extensions: amqp,apcu,ast,bcmath,bz2,calendar,core,ctype,curl,date,dom,enchant,exif,fileinfo,filter,ftp,gd,gettext,gmp,hash,iconv,igbinary,imagick,imap,intl,json,ldap,libxml,lzf,mbstring,mcrypt,memcache,memcached,msgpack,mysqli,oauth,oci8,opcache,openssl,pcntl,pcre,pdo,pgsql,phar,posix,raphf,pecl_http,readline,redis,reflection,session,shmop,simplexml,sockets,solr,spl,sqlite3,ssh2-beta,standard,sysvmsg,sysvsem,sysvshm,tokenizer,uuid,xdebug,xhprof,xml,xmldiff,xmlreader,xmlwriter,xsl,yac,zip,zlib
                        tools: phpunit

        name: Test DB References

        env:
            APP_ENV: dev  # see explains at https://github.com/llaville/php-compatinfo-db/issues/101
            DATABASE_URL: "sqlite:///%kernel.cache_dir%/compatinfo-db.sqlite"

        steps:
            -   # Git Checkout
                name: Checkout
                uses: actions/checkout@v3

            -   # Setup Libraries
                name: Setup Libraries
                run: |
                    sudo apt-get update
                    sudo apt-fast install libcurl4-openssl-dev -y
                    sudo apt-fast install libssh2-1-dev -y
                    sudo apt-fast install librdkafka-dev -y

            -   # Setup cache environment
                name: Setup cache environment
                id: extcache
                uses: shivammathur/cache-extensions@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}
                    key: cache-v4

            -   # Cache extensions
                name: Cache extensions
                uses: actions/cache@v3
                with:
                    path: ${{ steps.extcache.outputs.dir }}
                    key: ${{ steps.extcache.outputs.key }}
                    restore-keys: ${{ steps.extcache.outputs.key }}

            -   # Setup PHP runtime
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ matrix.extensions }}
                    tools: ${{ matrix.tools }}

            -   # Install Composer dependencies
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: "highest"
                    composer-options: "--prefer-dist --no-scripts"

            -   # Build Database
                name: Build Database
                run: |
                    bin/compatinfo-db db:create --ansi
                    bin/compatinfo-db db:init --ansi

            -   # Check Database
                name: Check Database
                run: |
                    bin/compatinfo-db diagnose --ansi
                    bin/compatinfo-db db:list --ansi

            -   # Run unit tests
                name: Unit tests
                run: bin/compatinfo-db doctor --ansi --with-tests
